apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    k8s-app: bokeh-demo
  name: bokeh-demo
  namespace: bokeh-demo
spec:
  replicas: 3
