apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: bokeh-demo-hpa
  namespace: bokeh-demo
spec:
  scaleTargetRef:
  name: bokeh-demo
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
  resource:
    name: cpu
    target:
      type: Utilization
      averageUtilization: 80
