apiVersion: v1
kind: Service
metadata:
 name: bokeh-frontend
 labels:
   k8s-app: bokeh-demo
spec:
 ports:
 - port: 8889
   protocol: TCP
   targetPort: 8888
 selector:
   k8s-app: bokeh-demo
 externalIPs:
   - 192.168.0.210

