apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  finalizers:
  labels:
    cattle.io/creator: norman
  name: bokeh-demo-s
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
