apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: bokeh
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  claimRef:
    name: nfs-pv
    namespace: bokeh
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /bokeh-data
    server: 192.168.0.45
