apiVersion: v1
kind: Service
metadata:
 name: kibana
 namespace: kube-logging
 labels:
   k8s-app: kibana
spec:
 ports:
 - port: 5601
 selector:
   k8s-app: kibana
 externalIPs:
   - 192.168.0.210
 type: NodePort
